export const SITE_CONFIG = {
  name: "Falcons Education System",
  tagline: "Quality Education from Play Group to Class 6 in Rawalpindi",
  description:
    "Falcons Education System — school in Rawalpindi for ages 3–12: Play Group to Class 6, Montessori early years, evening coaching up to Matric. Admissions open.",
  url: "https://falconseducationsystem.com",
  address: {
    street: "Street No 14, Sonari Bank, Kamalabad Road",
    landmark: "Near Bakra Mandi",
    city: "Rawalpindi",
    province: "Punjab",
    postalCode: "46000",
    country: "Pakistan",
    full: "Street No 14, Sonari Bank, Kamalabad Road, Near Bakra Mandi, Rawalpindi, Punjab, Pakistan 46000",
  },
  coordinates: {
    lat: 33.57489,
    lng: 73.03198,
  },
  social: {
    instagram: "https://www.instagram.com/falconseducationsystem/",
    facebook: "https://www.facebook.com/falconseducationsystem/",
    tiktok: "https://www.tiktok.com/@falconseducationsystem",
  },
  whatsapp: "https://wa.me/923119911288",
  phone: "+92 311 9911288",
  phonePTCL: "051-6129955",
  email: "falconseducationsystem@gmail.com",
  founded: "August 2024",
  mapEmbedUrl:
    "https://maps.google.com/maps?q=Falcons+Education+System+Kamalabad+Rawalpindi&z=16&output=embed",
  mapDirectUrl:
    "https://www.google.com/maps/search/?api=1&query=Falcons+Education+System+Kamalabad+Rawalpindi",
};

export const SEO_KEYWORDS = [
  "best school in Rawalpindi",
  "best children school Rawalpindi",
  "best school for class 1 to 6 Rawalpindi",
  "best primary school in Rawalpindi",
  "best Montessori school in Rawalpindi",
  "best preschool in Rawalpindi",
  "top schools in Rawalpindi",
  "best school near me Rawalpindi",
  "school Rawalpindi",
  "primary school Rawalpindi",
  "school up to class 6 Rawalpindi",
  "Montessori school Rawalpindi",
  "best school Rawalpindi",
  "Montessori preschool Rawalpindi",
  "preschool Rawalpindi",
  "playgroup school Rawalpindi",
  "nursery school Rawalpindi",
  "kindergarten Rawalpindi",
  "school Kamalabad Road Rawalpindi",
  "Falcons Education System",
  "Falcons Education System Rawalpindi",
  "school admission Rawalpindi",
  "primary school admission Rawalpindi",
  "coaching center Rawalpindi",
  "evening coaching classes Rawalpindi",
  "Saturday coaching Rawalpindi",
  "computer courses for kids Rawalpindi",
  "best school near Kamalabad Road",
  "school near Bakra Mandi Rawalpindi",
  "evening classes for kids Rawalpindi",
  "class 1 to 6 school Rawalpindi",
];
