export const SITE_CONFIG = {
  name: 'Falcons Education System',
  tagline: 'Quality School Education & Evening Coaching in Rawalpindi',
  description:
    'Falcons Education System provides quality school education and evening coaching classes in Rawalpindi. Programs include Nursery, Montessori, KG, Saturday Coaching, Evening Academy, and Computer Courses. Admissions open 2026.',
  url: 'https://falconseducationsystem.com',
  address: {
    street: 'Street No 14, Sonari Bank, Kamalabad Road',
    landmark: 'Near Bakra Mandi',
    city: 'Rawalpindi',
    province: 'Punjab',
    postalCode: '44000',
    country: 'Pakistan',
    full: 'Street No 14, Sonari Bank, Kamalabad Road, Near Bakra Mandi, Rawalpindi, Punjab, Pakistan 44000',
  },
  coordinates: {
    lat: 33.57489,
    lng: 73.03198,
  },
  social: {
    instagram: 'https://www.instagram.com/falconseducationsystem/',
    facebook: 'https://www.facebook.com/falconseducationsystem/',
    tiktok: 'https://www.tiktok.com/@falconseducationsystem',
  },
  whatsapp: 'https://wa.me/923119911288',
  phone: '+92 311 9911288',
  phonePTCL: '051-6129955',
  email: 'info@falconseducationsystem.com',
  founded: 'August 2024',
  mapEmbedUrl:
    'https://maps.google.com/maps?q=Street+14+Sonari+Bank+Kamalabad+Road+Rawalpindi+Pakistan&output=embed',
  mapDirectUrl:
    'https://www.google.com/maps/search/?api=1&query=Street+14+Sonari+Bank+Kamalabad+Road+Rawalpindi+Pakistan',
};

export const SEO_KEYWORDS = [
  'Montessori school Rawalpindi',
  'best Montessori school Rawalpindi',
  'Montessori preschool Rawalpindi',
  'preschool Rawalpindi',
  'playgroup school Rawalpindi',
  'nursery school Rawalpindi',
  'kindergarten Rawalpindi',
  'Montessori school Kamalabad Road',
  'Falcons Education System',
  'Falcons Education System Rawalpindi',
  'early childhood education Rawalpindi',
  'Montessori admission Rawalpindi',
  'preschool admission Rawalpindi',
  'coaching center Rawalpindi',
  'evening academy Rawalpindi',
  'evening coaching classes Rawalpindi',
  'Saturday coaching Rawalpindi',
  'tuition center Rawalpindi',
  'computer courses for kids Rawalpindi',
  'best school near Kamalabad Road',
  'preschool near Bakra Mandi Rawalpindi',
  'evening classes for kids Rawalpindi',
  'weekend coaching Rawalpindi',
  'Montessori method',
  'child-centered learning',
];
