export const SITE_CONFIG = {
  name: 'Falcons Education System',
  tagline: 'Quality Education from Nursery to Class 6 in Rawalpindi',
  description:
    'Falcons Education System is a school in Rawalpindi offering education from Nursery to Class 6, plus Evening Coaching, Saturday Coaching, and Computer Courses. Admissions open 2026. Located on Kamalabad Road.',
  url: 'https://falconseducationsystem.com',
  address: {
    street: 'Street No 14, Sonari Bank, Kamalabad Road',
    landmark: 'Near Bakra Mandi',
    city: 'Rawalpindi',
    province: 'Punjab',
    postalCode: '46000',
    country: 'Pakistan',
    full: 'Street No 14, Sonari Bank, Kamalabad Road, Near Bakra Mandi, Rawalpindi, Punjab, Pakistan 46000',
  },
  coordinates: {
    lat: 33.57489,
    lng: 73.03198,
  },
  social: {
    instagram: 'https://www.instagram.com/falconseducationsystem/',
    facebook: 'https://www.facebook.com/falconseducationsystem/',
    tiktok: 'https://www.tiktok.com/@falconseducationsystem',
  },
  whatsapp: 'https://wa.me/923119911288',
  phone: '+92 311 9911288',
  phonePTCL: '051-6129955',
  email: 'info@falconseducationsystem.com',
  founded: 'August 2024',
  mapEmbedUrl:
    'https://maps.google.com/maps?q=Street+14+Sonari+Bank+Kamalabad+Road+Rawalpindi+Pakistan&output=embed',
  mapDirectUrl:
    'https://www.google.com/maps/search/?api=1&query=Street+14+Sonari+Bank+Kamalabad+Road+Rawalpindi+Pakistan',
};

export const SEO_KEYWORDS = [
  'school Rawalpindi',
  'primary school Rawalpindi',
  'school up to class 6 Rawalpindi',
  'Montessori school Rawalpindi',
  'best school Rawalpindi',
  'Montessori preschool Rawalpindi',
  'preschool Rawalpindi',
  'playgroup school Rawalpindi',
  'nursery school Rawalpindi',
  'kindergarten Rawalpindi',
  'school Kamalabad Road Rawalpindi',
  'Falcons Education System',
  'Falcons Education System Rawalpindi',
  'school admission Rawalpindi',
  'primary school admission Rawalpindi',
  'coaching center Rawalpindi',
  'evening coaching classes Rawalpindi',
  'Saturday coaching Rawalpindi',
  'computer courses for kids Rawalpindi',
  'best school near Kamalabad Road',
  'school near Bakra Mandi Rawalpindi',
  'evening classes for kids Rawalpindi',
  'class 1 to 6 school Rawalpindi',
];
